task: dti
model:
  name:dtimodel
data:
  mol:
    featurizer: cnn
    config_path: configs/encoders/mol/cnn.json
  name: dti
  path: datasets/dti/Yamanishi08
  smiles_max_length: 100
  
dataset:
  name: Yamanishi08
  path: datasets/dti/Yamanishi08
  mol:
    name: cnn
    config_path: configs/encoders/mol/cnn.json
  protein:
    name: transformer
    config_path: configs/encoders/protein/transformer.json
train:
  epochs: 100
  batch_size: 100
  lr: 0.0001
  optimizer: Adam
  loss: MSE
  early_stopping:
    patience: 5
    min_delta: 0.001
  lr_scheduler:
    factor: 0.5
    patience: 2 
